<? $this->headScript()->appendFile("/library/js/jquery.FCKEditor.js");?>
<? $this->headScript()->captureStart(); ?>
    $(function(){
        $.fck.config={ path:'/library/fckeditor/', width: 800, height: 600, Config: { CustomConfigurationsPath: '/library/fckeditor/Core_Api_config.js' }};
    	$("textarea[name='Content[content]']").fck({toolbar: 'Core_Api_toolbar'});
        $.fck.update(); // update value in textareas of each FCK editor instance
    });
<? $this->headScript()->captureEnd(); ?>

    <h2><?= $this->placeholder('title');?><?if (!empty($this->Content->title)):?> - "<?=$this->Content->title;?>"<?endif;?></h2>
    <a href="<?=$this->url(array('action'=>'list'));?>">Return To List</a>
    <?= $this->form ?>

