	<div class="footer">
		<div class="footer-level-2">
		
			<!-- begin footer -->
			
			<p>
				<a href="/">Home</a></li>
				<a href="/content/display/show/slug/problems-and-solutions" title="Problems & Solutions">Problems & Solutions</a>
				<a href="/content/display/show/slug/sandbox" title="Development, Experimental, Sandbox">Sandbox</a>
				<a href="/contact/request" title="Contact Me">Contact Me</a>
			</p>
			
			<!-- end footer -->
			
		</div>
	</div>
	<div class="page-end">
		<!-- begin page end -->
		<p>&copy; Lance Caraccioli 2008-<?=date('Y');?>. Design: <a href="http://www.spyka.net" title="spyka Webmaster">spyka webmaster</a></p>
		<!-- end page end -->
	</div>
