<?= $this->doctype() ?>
<? $this->navigation()->getContainer()->addPages(new Zend_Config_Xml(APPLICATION_PATH . "/configs/navigation.xml")); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<? //identify active page
$activePage = $this->navigation()->findActive($this->navigation()->getContainer());
?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <?= $this->headTitle($activePage['page']->label . ' | Lance Caraccioli - Web Applications Developer - Web Systems Engineer - Software Developer - Baton Rouge - Hammond - Louisiana'); ?>
    <?
    $this->headScript()
        //->prependFile('/library/js/nicEdit/nicEdit.js')//still some bugs here with this version maybe port to jquery???
        ->prependFile('/library/syntaxhighlighter_2.1.364/scripts/shBrushPhp.js')
        ->prependFile('/library/syntaxhighlighter_2.1.364/scripts/shCore.js')
        ->prependFile('/library/js/site.js')
        ->prependFile('/library/js/jquery.form.js')
        ->prependFile('/library/js/jGrowl-1.2.0/jquery.jgrowl.js')
        ->prependFile('/library/js/smarterer-popup.js')
        ->prependFile('/library/js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js')
        ->prependFile('/library/js/jquery-ui-1.10.3.custom/js/jquery.min.js')
        ;
    ?>
    <? $this->headScript()->captureStart(); ?>
    <? $messages = $this->notifier()->getMessages(); ?>
    <? if (!empty($messages)): ?>
        $('document').ready(function(){
        var messages = <?= Zend_Json::encode($messages); ?>;
        displayMessages(messages);
        });
    <? endif; ?>
    <? $this->headScript()->captureEnd(); ?>
    <?=
    $this->headLink()
        ->appendStylesheet('/library/css/yui-reset-font-grids.css')
        ->appendStylesheet('/library/css/yui-base.css')
        ->appendStylesheet('/layouts/css/styles.css')
        ->appendStylesheet('/layouts/css/navigation.css')
        //->appendStylesheet('/library/css/forms.css')
        ->appendStylesheet('/library/js/jGrowl-1.2.0/jquery.jgrowl.css')
        ->appendStylesheet('/library/js/jquery-ui-1.7.2.custom/css/sunny/jquery-ui-1.7.2.custom.css')
        ->appendStylesheet('/library/syntaxhighlighter_2.1.364/styles/shCore.css')
        ->appendStylesheet('/library/syntaxhighlighter_2.1.364/styles/shThemeMidnight.css')
        ->appendAlternate('http://' . $_SERVER['SERVER_NAME'] . '/content/feed', 'application/rss+xml', "Mr Burly's Sandbox");
    ?>


    <?= $this->headStyle(); ?>
</head>
<body>
<div id="wrap">
    <?= $this->render('header.phtml') ?>
    <div id="page">
        <div id="main-content">
            <p><?= $this->navigation()->breadcrumbs(); ?></p>
            <? if ($activePage['page']): ?><h2><?= $activePage['page']->label; ?></h2><? endif; ?>
            <?= $this->placeholder('layout-content'); ?>
        </div>
        <div id="main-sidebar">
            <?= $this->navigation()->menu()->renderSubMenu(); ?>
            <?= $this->render('side-bar.phtml') ?>
        </div>
        <div class="clear"></div>
    </div>
    <?= $this->render('footer.phtml') ?>
</div>
<? $this->headScript()->captureStart(); ?>
(function($){
$(document).ready(function(){
SyntaxHighlighter.all();
});
})(jQuery)
<? $this->headScript()->captureEnd(); ?>

<? //based on best practice recommendations from yahoo.?>
<?= $this->headScript(); ?>
<? if (false === strpos($_SERVER['SERVER_NAME'], '.localhost')): ?>
    <script type="text/javascript">
        var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
        document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
        try {
            var pageTracker = _gat._getTracker("UA-12087022-1");
            pageTracker._trackPageview();
        } catch (err) {
        }
    </script>
<? endif; ?>
</body>
</html>
