<!-- being sidebar content -->
<div class="sidebar-box">
	<h4>@mrBurly on twitter</h4>
	<?=$this->action('status-updates-list', 'feed', 'twitter');?>
</div>
<div class = "sidebar-box brown-box" style="text-align:center;">
	<ul class="icons">
		<li><a href="http://zend.com/zce.php?c=ZEND012264&r=232542699" target="_blank"><img title="Verify my status as a Zend Certified Engineer" src = "/images/3rd-party-buttons/php5_zce_logo_new.gif" /></a></li>
		<li><a href="/resume" ><img alt="View/Download My Online Resume" title="View/Download My Online Resume" src = "/images/3rd-party-buttons/my-resume.jpg" /></a></li>
		<li><a href="http://alistapart.com/articles/survey2009" target="_blank"><img title="take the survey for web development professionals" src = "/images/3rd-party-buttons/i-took-the-2009-survey.gif" /></a></li>
	</ul>
</div>	
<div class="sidebar-box">
	<h4>kudos</h4>
	<ul>
		<li><a href="http://www.spyka.net" title="spyka Webmaster resources">Spyka</a> - open source designs for non designers.</li>
		<li><a href="http://www.jquery.com" title="Magic">Jquery</a> - the way javascript was meant to be.</li>
		<li><a href="http://alexgorbatchev.com/wiki/SyntaxHighlighter" title="SyntaxHighlighter">SyntaxHighlighter</a> - inline code snippet syntax highlighting.</li>
		<li><a href="http://www.pastie.org" title="Pastie.org">Pastie</a> - code snippet syntax highlighting and sharing.</li>
		<li><a href="https://worleyco.com/" title="Where I Work">Worley Catastrophe Response</a> - work.</li>
	</ul>
</div>

<!-- end sidebar content -->
