<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
    <div class="paginationControl">
    	<a class="current label">PAGE:</a>
        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url(array('page' => $this->previous)); ?>">
                &lt;&lt;
            </a>
        <?php else: ?>
            <?php //<a class="disabled">&lt;&lt;</a>?>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
               <a class="current"><?= $page; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array('page' => $this->next)); ?>">
                &gt;&gt;
            </a>
        <?php else: ?>
            <?php //<a class="disabled">&gt;&gt;</a> ?>
        <?php endif; ?>
    </div>
<?php endif; ?>