<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Content_Model_Base_Content extends Doctrine_Record
{
	public function setTableDefinition()
    {
	    $this->setTableName('content');
		$this->hasColumn('id', 'integer', 11, array('type'=>'integer', 'length'=>11, 'primary' => true,'autoincrement' => true));
		$this->hasColumn('title', 'string', 255, array('type' => 'string','length' => 255));
		$this->hasColumn('content', 'string', null , array('type' => 'string'));
		$this->hasColumn('slug', 'string', 255,array('type' => 'string','length' => 255));
	    $this->hasColumn('publish_date', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
	    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
	    $this->hasColumn('updated', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
	}

	public function setUp()
    {
		$sluggable0 = new Doctrine_Template_Sluggable(array('fields' => array(0 => 'title'), 'canUpdate' => true, 'name' => 'slug', 'type' => 'string', 'length' => '255', 'unique'=>true));
		$this->actAs($sluggable0);

	    $timestampable0 = new Doctrine_Template_Timestampable(array('created' => array('name' => 'created'), 'updated' => array('name' => 'updated')));
	    $this->actAs($timestampable0);
	    
	    $this->actAs('SoftDelete');
	}
}
