<h3>Working Smart, Not Hard</h3>
<p>
	Working hard is ingrained in me like many Americans.  I was raised with the firm belief that I could do anything, but I was going 
	to have to work for it.  It took me a long time to learn that working hard isn't enough.  You also have to work smart.<span class="more">
	"What do you mean when you say smart?"  Let's think about an example.  Let's say I wanted to be the next Major League power hitter.  I want to 
	hit more home runs than Sammy Sosa, or Mark Maguire.  What are my options?  Well the typical solution is to work out as much 
	as possible and get as large as I can so that I can take a crappy swing and force balls over the fence with raw might.  However
	<a href="http://en.wikipedia.org/wiki/Roger_Maris">Roger Maris</a> (the guy whose home run record they beat) weighed 204 lbs.
	He didn't muscle the ball out of the stadium, instead he used a fine tuned swing to take advantage of the resources he already had
	no doubt due to hard work, but also smart work.  This concept of smart work is key to a minimalistic approach, and also key 
	to building maintainable, readable, portable code and still deliver on time.</span>
</p>