<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediaGallery_Model_Album extends MediaGallery_Model_Base_Album
{
	public function preDqlSelect($event){
		$Association = Zend_Registry::isRegistered('Association')?Zend_Registry::get('Association'):null;
		if ($Association){
			$query = $event->getQuery();
			$params = $event->getParams();
			$tableAlias = $params['alias'];
			if (!$query->contains($tableAlias.'.association_id')) {
				$query->addWhere($tableAlias.'.association_id = ?',$Association->id);
			}
		}
	}
  
	public function preInsert($event){
		$Association = Zend_Registry::isRegistered('Association')?Zend_Registry::get('Association'):null;
		if ($Association){
			$event->getInvoker()->association_id = $Association->id;
		}
	}

	public function preUpdate($event){
		return $this->preInsert($event);
	}
}
