<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class MediaGallery_Model_Base_Album extends Doctrine_Record
{
	
  public function setTableDefinition()
  {
    $this->setTableName('mediagallery_album');
    $this->hasColumn('id', 'integer', 11, array('primary' => true, 'autoincrement' => true, 'type' => 'integer', 'length' => '11'));
    $this->hasColumn('cover_photo_id', 'integer', 11, array('type' => 'integer', 'length' => '11'));
    $this->hasColumn('name', 'string', 100, array('type' => 'string', 'length' => '100'));
    $this->hasColumn('description', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
  }

  public function setUp()
  {
  	$this->hasMany('MediaGallery_Model_Media as Media', array('local' => 'id','foreign' => 'media_album_id'));
    $this->hasOne('MediaGallery_Model_Media as CoverPhoto', array('local' => 'cover_photo_id', 'foreign' => 'id'));

    $this->actAs('Timestampable');
  }
  

}
