<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class MediaGallery_Model_Base_Media extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('mediagallery_media');
    $this->hasColumn('id', 'integer', 11, array('primary' => true, 'autoincrement' => true, 'type' => 'integer', 'length' => '11'));
    $this->hasColumn('media_album_id', 'integer', 11, array('type' => 'integer', 'length' => '11'));
    $this->hasColumn('name', 'string', 100, array('type' => 'string', 'length' => '100'));
    $this->hasColumn('uploaded_filename', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('type', 'string', 100, array('type' => 'string', 'length' => '100'));
    $this->hasColumn('caption', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
	$this->hasColumn('crop_left', 'integer', 11, array('default'=>0));
	$this->hasColumn('crop_top', 'integer', 11, array('default'=>0));
	$this->hasColumn('crop_width', 'integer', 11, array('default'=>100));
	$this->hasColumn('crop_height', 'integer', 11, array('default'=>100));
  }

  public function setUp()
  {
    $this->hasOne('MediaGallery_Model_Album as Album', array('local' => 'media_album_id','foreign' => 'id'));
    $this->actAs('Timestampable');
  }
}
